### ISSUE TITLE
Tutorial calls BrukerFile() which is not defined

### ISSUE THREAD

**Issue by MattEttus** [MagneticResonanceImaging/MRIRecoTutorial#2]
I'm on Julia 1.7.3, and MRIReco does not seem to have a function called BrukerFile.  The tutorial pluto worksheet stops at the first call to it.

**Comment by tknopp** [comment]
Thanks! This is actually expected since the notebook is outdated. We decided to keep it as is and instead move all of it's content to the MRIReco documentation. To make this clear I added a warning text to this repo:
https://github.com/MagneticResonanceImaging/MRIRecoTutorial/commit/b2169d394b36c66e80c22f5e4912379b06fb1978
